### PR TITLE
Created Unit Tests Project

### PR DESCRIPTION
**Pull request by 65001**
The Unit Testing project will make future changes to an API easier. Whenever I change a file or add functionality I will add one of these to ensure that testing is easier. To test this within Visual Studio you can go to `Test>Run>All Tests` or press `Ctrl+R,A`. 

This code assumes the latest version of LDHashTables which returns "" when given an incorrect key, however that relevant code is not included in my version to prevent a merge conflict.

### CODE REVIEW

**Comment by litdev1** [comment]
This merge breaks my environment - maybe due to changes in solution, im still using vs2017.

**Comment by 65001** [comment]
Is one of the solutions not loading correctly ? I will investigate on my end.

**Comment by litdev1** [comment]
Yes the new test settings project

I tried adding it as a new project and installing nuget NUnit.

It compiles but on run test I get
e sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

**Comment by 65001** [comment]
I commited my `.csproj` file. Hopefully that will fix the error?
I also didn't use NUnit, I just used the MS Visual Studio Test system.

**Comment by litdev1** [comment]
I got past my last error and the tests run - when I force an assert (fail) I don't see any indication - how do you see results?

**Comment by 65001** [comment]
`Test>Windows>Test Explorer` or `Ctrl+E,T` that should bring up the results.

**Comment by litdev1** [comment]
Great this works - nice to have this - thanks
I will commit this then you can add the test.cs are you create - I think our environements are different so merging solutions/projects will be tough

tests

**Comment by 65001** [comment]
Yeah, I will keep that in mind and limit my additions to `.cs` files whenever I can.

**Pull request closed without merging**
