### PR TITLE
LDServer.Brodcast Function

### PR DESCRIPTION
**Pull request by 65001**
I would make these pull requests larger but currently I am having CS0016 errors when trying to complie LitDev and am hence trying to keep my changes more on the small side.

Also on [Utlitites L121 ish](https://github.com/litdev1/LitDev/blob/master/LitDev/LitDev/Utilities.cs#L121) could you use a switch statement instead of the `if {} else if {}` block right there?

### CODE REVIEW

**Comment by litdev1** [comment]
I'm not really up to speed on handling GitHub with merge requests - I tried adding your last one and it didn't filter through to the code on my PC so I just added something similar manually.

The if to case - sure but no real change or performance improvement so not really a priority.

Not sure exactly what you are doing with the broardcast bits.  Suggest at present keep requests to separate requests and the next one I will try to commit again using merge, but if I have to redo locally not sure what is happening and not keen to mess about too much if not sure what it is doing.

**Comment by 65001** [comment]
The idea with the Broadcast function would be to send out messages to all connected clients on a Server.
Have you synced your code with your github repo ? That's usually what I do to synce up my code... I agree however that using git can be confusing at times.

**Review by litdev1 — APPROVED** [review]
try to approve

**Comment by litdev1** [comment]
Yes I synced but it didn't come through - I probably did something wrong but it seems less intuative than TFS that I normally use.  Trying again with the broadcast.

For the CS error - it would be good to get this going so you can test - ideas

1] make sure solution is release x86 (even on 64 bit pc)
2] maybe install [SlimDX .Net 4 x64](http://slimdx.org/download.php)
3] Which project fails?

**Comment by litdev1** [comment]
This seemed to work - Broadcast (renamed from Brodcast) came through and I uploaded to beta - perhaps test it.

So I can use the GitMerge now!  Please try to keep requests separate - easier to merge and track.

**Comment by 65001** [comment]
I installed Slim DX. Net x64 as you asked and it did not fix any problems. 
Here is what Xamarian Studio is telling me.

<ul>
	<li>Warnings:
		<ol>
			<li>
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
			</li>
			<li>
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "SlimDX, Version=4.0.13.43, Culture=neutral, PublicKeyToken=b1b0c32fd1ffe4f9, processorArchitecture=AMD64", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
			</li>
		</ol>
		</li>

<li>Errors:
<ul>
<li>
CSC : error CS0016: Could not write to output file 'C:\Users\$UserName\Documents\GitHub\LitDev\LitDev\bin\Debug\LitDev.XML' -- 'Could not find a part of the path 'C:\Users\$UserName\Documents\GitHub\LitDev\LitDev\bin\Debug\LitDev.XML'.'
</li>
</ul>
</li>

I shall test it asap

**Comment by litdev1** [comment]
I use Visual Studio Community 2015 not Xamarian, perhaps this is part of the problem, the error looks like file paths or permissions - check these - maybe try running VS as admin but you shouldn't need to I don't.

**Comment by 65001** [comment]
Thanks Litdev(Steve) for your help. It was a file system issue after all.
By the way you might want to remove the hard-coded file paths in the Test Harness, it reveals stuff like your windows username.

**Comment by litdev1** [comment]
I don't really care about my user name path - its not a secret - thanks for mentioning anyway.  The testharness is just a random set of stuff I tried at various points - probably not much use for anyone but me.  The main use is to be able to get into extension code in a debugger.

**Pull request merged**
