### PR TITLE
Replaced hardcoded dll dependencies with Nuget Packages

### PR DESCRIPTION
**Pull request by 65001**
This is important to make the project portable.

Additionally I added LDHashtables which should allow SB users to access Dictionaries which I do believe til now was not accessible via API. 

If you want to merge this manually please add me as a coauthor to the commit.

### CODE REVIEW

**Comment by litdev1** [comment]
Hi,
I'm happy to add these but have had issues with github before - I don't really use it and am nervous pressing buttons.
So if I hit "Merge pull request" - which option then do I choose and add as coauthor - no idea how to do this.
If you can give me a couple instructions I am happy to try, but in the past I have broken compile and struggled to revert.
Usually I just add code manually - several from Pappa Lapub - I know what I am doing that way and how to test before committing.
Ideally I would like to get the code changes and test before committing anything.

**Comment by 65001** [comment]
[How to merge a pull request](https://help.github.com/articles/merging-a-pull-request/).
If you choose to use the github merge you can ignore adding me as a co author. 

If you choose to add code manually like you do from Pappa Lapub and you have Github Desktop [you can do it like this](https://desktop.github.com/features/co-authors/).

In the event you need to [revert a commit](https://help.github.com/desktop/guides/contributing-to-projects/reverting-a-commit/)

May I ask if you use SVN at work? 

If you tell me how you test your code I can set it up so that it ensures that any future code changes don't break anything.  I would hope to achieve this through Travis CI.

If you have any further questions or if I could in anyway be of assistance please ask.

**Comment by litdev1** [comment]
I have merged successfully from VS - great.
Tesing is really just that it works as expected and conforms to any general rules that make methods have a similar kind of arguments and work with any other methods that they should - not an issue for a new standalone object as in this case.  For eaxmple that you can make several hash tables as you have done.
Also I update 'whats new and maybe other documentation'.
My test:
LDHashTable.Add("test","A",1)
LDHashTable.Add("test","B",1)
LDHashTable.Add("test","C",2)
TextWindow.WriteLine(LDHashTable.GetValue("test","B"))
TextWindow.WriteLine(LDHashTable.ContainsKey("test","B"))
TextWindow.WriteLine(LDHashTable.ContainsKey("test","D"))
TextWindow.WriteLine(LDHashTable.ContainsValue("test","1"))
TextWindow.WriteLine(LDHashTable.ContainsKey("test",3))
TextWindow.WriteLine(LDHashTable.Remove("test","B"))
TextWindow.WriteLine(LDHashTable.GetValue("test","B"))
TextWindow.WriteLine(LDHashTable.Clear("test"))
TextWindow.WriteLine(LDHashTable.GetValue("test","B"))
This crashes on GetValue line so will add a little protection.

All good - uploaded as beta build and commited
Cheers.
I use TFS at work.

**Comment by 65001** [comment]
Do you mind if I start to set up continuous integration in other pull requests? It would allow easier testing for more collaborators.

**Comment by litdev1** [comment]
what does that mean?  Sorry I really only use github as version control and to make souce open, not really for collaboration.

**Comment by 65001** [comment]
Well continuous integration is a form of testing like you posted above but it ensures that any commit or pull request passes all the tests you have set up. So if I changed the logic of say LDServer and I did it correctly it would tell you on this page that I haven't broken that part of the code base. It is basically automated unit testing that everyone can see the results of.

Also is there any part of the repo you specifically want worked on etc? I want to contribute to this wonderful endeavour. It helped me learn to code after all!

**Comment by litdev1** [comment]
Testing needs SB to be started in most cases - usually I do testing manually like I did here and then don't really need to do again unless this feature changes or a bug is reported.
I don't really have any ideas on new stuff at present, but am very happy for you to add stuff - I would prefer that it wasn't refactoring of existing objects as this does entail more testing.
Perhaps utilities for games - LDGame
shape collison events - background music - handling multiple sprites and their movement (normally needs large multi-dimensional arrays - slow) - tricky!
Or specific objects with information using online APIs - maybe like star map, geographical data like countries and capitals etc
I'm just thinking - perhaps these are not practical but would be a challenge to think through.

**Pull request merged**
