### PR TITLE
Minor changes and small refactors

### PR DESCRIPTION
**Pull request by 65001**
Hopefully you will merge these changes, I worked on them for a bit...
Is there anywhere in the repo that needs work or attention in particular? It would be an interesting challenge for me to try and optimize and the like.

Also GNU question for you: Under the current GNU GPL v3 license the project is licensed under anybody that uses LitDev has to release the code and licence their respective code under the GNU GPL v3. Is that understanding true? If it is I would suggest considering moving to the GNU Lesser General Public License if that was not the intent.

### CODE REVIEW

**Comment by litdev1** [comment]
Hi,
I don't find this github merging very easy - all I have done so far is mess up my own builds with incompatible merges :(

I quite like the license that keeps open source open.

Unless I find a way to handle and test merges easily, I'm not so keen on merging refactorings like stringbuilder unless there is a noticable performance improvement.

So first I will try so resort git and my local builds then have a look at merges, but for now I don't trust git and will have to do it all manually - hence not so keen on cosmetc changes.

**Comment by 65001** [comment]
Correct me if I'm wrong but when you loop a string doesn't the mutable vs immutable difference between string & string builder come into play making string builder significantly faster for larger amounts of data?

I just dislike the virus nature of the GNU I guess. It seems forced to me.

**Comment by litdev1** [comment]
You are right for larger amounts of data - it is still probably marginal in the context of SB.  I will manually make this change for LDDatabase.

The else return in LDUtilities I think is needed
The Dialogs ToString is OK but could be either.

The boardcast is really just cosmetic and possibly even slower due to the return result not used.

I am just struggling with git merging and don't really trust it since it mucked me up.

**Comment by 65001** [comment]
I think I fixed the merge conflicts on my end so you should be able to automerge it now?

**Comment by litdev1** [comment]
I don't want to auto merge - it took me 1/2 hour to fix last one, it overwrote and removed other changes I had made.  I don't understand or trust git auto merging - I want to see what is changed and not given automatic choices I don't understand like merge and pull, quash and merge, rebase and merge?
Frankly I would prefer a copy of the changes in text I can compare with a proper merging tool.
**Are there any requests that are not cosmetic** - i.e affect how the code actually works.

**Comment by 65001** [comment]
The only stuff I added was LDText which gives an interface for StringBuilder for sb. I believe you can view a text version of the changes in the Files Changed tab

**Comment by litdev1** [comment]
What is the reason for this since the interface methods aren't used anywhere and if they were it what is the advantage over the standard Text.Append since it would be converted to Primitive type anyway?  Have you done performance test to show it is noticably faster?

**Comment by 65001** [comment]
It's a slightly different use case.
Text Append takes two inputs & returns a primitive while LDTEXT.Append takes one & returns void. Meaning you can put the Append in a loop & to string it once it's over.. If that makes sense...

I'll make a test to show the difference

**Comment by 65001** [comment]
Also for future testing purposes how would I merge all the dll files into the LD.dll file?

Here is a text I wrote in C# that should show some of the performance differences. It should have the same characteristics as that of the proposed changes.

```C#
using System;
using System.Text;
using System.Diagnostics;
using Microsoft.SmallBasic.Library;

namespace Test
{
    static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        static void Main()
        {
            Stopwatch TimeSB = new Stopwatch();
            TimeSB.Start();
            StringBuilder sb = new StringBuilder();
            int Limit = 13830;
            //String Builder Like that proposed for LDText
            sb.AppendLine("1 to "+ Limit+":");
            for (int i = 1; i < Limit; i++)
            {
                sb.Append(i.ToString());
            }
            sb.ToString();
            TimeSB.Stop();
            //SB Default Primitive
            Stopwatch TimeText = new Stopwatch();
            TimeText.Start();
            Primitive SampleText = "1 to " + Limit +":";
            for(int i =1;i < Limit; i++)
            {
                SampleText += i;
            }
            TimeText.Stop();
            //Text Append
            Stopwatch SmallBasicText = new Stopwatch();
            SmallBasicText.Start();
            Primitive SBText = "1 to " + Limit + ":";
            for (int i = 1; i < Limit; i++)
            {
                SBText = Text.Append(SBText, i);
            }
            SmallBasicText.Stop();

            Console.WriteLine();
            Console.WriteLine("Ticks for String Builder {0} ticks \nTicks for Primitive {1} ticks\nTicks for Text.Append {2} ticks", TimeSB.ElapsedTicks, TimeText.ElapsedTicks,SmallBasicText.ElapsedTicks);
            Console.WriteLine();
            Console.WriteLine("Time for String Builder {0} ms \nTime for Primitive {1} ms\nTime for Text.Append {2} ms", TimeSB.ElapsedMilliseconds, TimeText.ElapsedMilliseconds, SmallBasicText.ElapsedMilliseconds);
        }
    }
}
```
Here was the output I recieved:
```
Ticks for String Builder 8701 ticks 
Ticks for Primitive 525194 ticks
Ticks for Text.Append 510119 ticks

Time for String Builder 2 ms 
Time for Primitive 162 ms
Time for Text.Append 157 ms
```

**Comment by litdev1** [comment]
You need ILMerge.exe in the lib folder and use the MergeLitDev.bat file.  From the TestHarness window hit 'Copy dll and xml" then "Combine dlls" should do it.

**Comment by 65001** [comment]
I updated my tests to be a bit better..
I will download this ILMerge.exe and try everything out.

**Comment by litdev1** [comment]
I coded a quick test and running in SB - results look good

dim = 100000
txt = "My test string"
sw = LDStopwatch.Add()

LDStopwatch.Restart(sw)
data = ""
For i = 1 To dim
  data = Text.Append(data,txt)
EndFor
TextWindow.WriteLine("Text.Append "+LDStopwatch.ElapsedMilliseconds(sw))
TextWindow.WriteLine(Text.GetLength(data))

LDStopwatch.Restart(sw)
LDText.FastStringClear()
For i = 1 To dim
  LDText.FastStringAppend(txt)
EndFor
data = LDText.FastStringGet()
TextWindow.WriteLine("LDText.FastString "+LDStopwatch.ElapsedMilliseconds(sw))
TextWindow.WriteLine(Text.GetLength(data))

'Results are as you expected for large number of appends
'Text.Append 54155
'1400000
'LDText.FastString 41
'1400000

**Pull request closed without merging**
