### PR TITLE
Updates to LDHashtable

### PR DESCRIPTION
**Pull request by 65001**
Added static extension methods for ToPrimitiveArray which should enable future additions to the library to easily convert data to a primitive array.

### CODE REVIEW

**Comment by litdev1** [comment]
Loads of refactoring and changing to static Utilities.
Probably all great, but I'm not keen to change stuff I know works to make code look 'nicer'.
Unforseen issues - lots of work to test, with nothing any user will see apart from possible unforseen issues.  The thing about unforseen issues is they are unforseen and therefore extensive checking and testing is needed to code changes.  This is different to code additionsthat add feature that were not there before and cannot affect anything already there.
I kind of do this for fun and checking/testing loads of refacting isn't really fun.

**Comment by 65001** [comment]
I kept the fact you dislike needless refactors in mind when writing these changes. All of these changes should significantly increase performance or add features.

Commit bc069fc lets SB users convert a Hashtable to a SB Primitive Array. Tests for this are included in the Unit Tests.

Commit 9e1517d and cad9708 target critical code such as the Split method in LDText to enable much faster execution times. The LDText.Split method for example previously used normal string concatenation is much slower compared to using StringBuilder.

Commits f3dc0d3 and 1304ddb reduce CSV read times from 300 ms to 30 ms. The file was 12 by 986.

If I can prove with test coverage that most of these changes don't break anything would that help?

**Comment by litdev1** [comment]
Ok I committed, built and uploaded as beta build.
Please test a bit - I'm sure its fine, just don't fancy really working through it - super lazy.

**Comment by 65001** [comment]
I understand completely.

**Pull request merged**
