### PR TITLE
StringBuilders

### PR DESCRIPTION
**Pull request by 65001**
Added string builders to code that use loops.
Please ignore the server changes as I have not figured out how to overwrite them with the master branch.

Major Changes :
- Array.cs 
    - **Copy to SbArray** should be faster with scale
- Database.cs
    - **Query** : Possible improvement if the **Primitive _results_** was completely converted to a string builder  
- File.cs 
    - **Get Directories** and the like in recursion. Passed string builder via reference and not value

### CODE REVIEW

**Review by litdev1 — COMMENTED** [review]
Dialogs - no effect (casting is implied)
Utilities - the else is needed

**Review by litdev1 — COMMENTED** [review]
Server - no benefit, maybe slower

**Review by litdev1 — COMMENTED** [review]
Database - added manually
Text - added similar manually - thanks for this, it has added functionality

**Review by litdev1 — COMMENTED** [review]
File - Looks good - will change manually - I don't trust any auto Git merging

**Comment by 65001** [comment]
Question for you since I'm new at C#, does the compiler optimize away redundant casts?

**Comment by litdev1** [comment]
yes the generated runtime code will be the same - we only need to manually cast when the compiler has several choices and doesn't know what you want.  This usually happens when methods are overloaded (polymorphism) or classes are derived from parent classes (inheritance).
My prefenence is to only explicitly cast when it is needed - i.e. the compiler complains.
I updated the Text and FIle with your suggestions - thanks.

**Comment by 65001** [comment]
Your welcome & Thanks for the explanation. Is there any plans for updating the Array & Database files? Improved query speed would be pretty amazing

**Comment by litdev1** [comment]
Yes I did the database too, forgot to mention.  I will also just did the array ones.  Thanks.

**Comment by 65001** [comment]
@litdev1 I think you forgot to commit the changes for the Query part for LDDatabase

**Pull request closed without merging**
